### ISSUE TITLE
Payment request BTC LOST!! HELP!

### ISSUE THREAD

**Issue by systemsbeat** [keepkey/multibit-hd#907]
Hello. 
I am new to MULTIBIT HD, I made a payment request, send the address and the customer paid me but, when I was trying to restore my wallet multibit, by accident I deleted the payment request. Now the person sent me the btc to that address but in my wallet I didn't received anything, can you please help me?? Is there any way to restore that address and the payment sent to it?
Please I need my BTC!
Thank you.

**Comment by bgok** [comment]
Please contact support at https://keepkey.freshdesk.com/support/solutions. Based on what you have described, your bitcoins should be safe. Support can help you work through what you need to do next.

Thanks

**Comment by systemsbeat** [comment]
Thank you,  I have just sent message for help, I have no idea what I should do to recover my btc.
Thank you for your quick response!

**Comment by 99bits** [comment]
I have a similar problem.  I made a request, then sent the bitcoins to my wallet,  waited for a while, nothing came so I did a repair.  Now I don't have the history of the request and cannot receive the bitcoins.   Please help, what can I do.

**Comment by kliyer** [comment]
Hi 99 bits sorry to hear that you are facing issues with MultiBit. I would suggest you contact support at https://keepkey.freshdesk.com/support/solutions

**Comment by Romsontech** [comment]
@systemsbeat 
@99bits 
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : walletsrecoveryservice@gmail.com

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
