### ISSUE TITLE
Unconfirmed transaction

### ISSUE THREAD

**Issue by mpomam** [keepkey/multibit-hd#909]
Bug report
  Operating System:
  MultiBit HD Version:
  Steps to replicate the problem:
1. Add your steps here

Please help me. My BTC 0.049597500 transaction that was sent to me from Bitcoin on 28 June 2016 is still not confirmed in my wallet. Please help me so that I can make my payments.
My email address is mamrantham@gmail.com
![unconfirmed transaction](https://cloud.githubusercontent.com/assets/20375066/16710491/dc931b16-4630-11e6-92a3-8dcf782dee6d.png)
![unconfirmed transaction 2](https://cloud.githubusercontent.com/assets/20375066/16710496/e900b91c-4630-11e6-8ce3-83037e741676.png)

**Comment by tshe** [comment]
Go to manage wallet and repair your wallet. Should work.

**Comment by ghost** [comment]
This still happens in 0.5.0 beta. 

New incoming transactions are always **unconfirmed**.

**Comment by kliyer** [comment]
Hi kensenjiha , sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.

**Comment by doge2021** [comment]
there is a bug in old multibit wallet. you can refer more info: https://btc2doge.org/2023/02/multibit-hd-wallet-seed-words-not-work/
