### ISSUE TITLE
My BTC balance got into unconfirmed account  

### ISSUE THREAD

**Issue by tshe** [keepkey/multibit-hd#910]
Bug report 
Operating System: OSX EI Capitan version 10.11.4
MultiBit HD Version: 0.3.X

Steps to replicate the problem:

1. I have little more than 3BTC in my wallet, on 12th July have transferred 1 BTC to my another account and transaction was success. 

2. Today 14th July, I signed into my account and was trying to transfer remaining 2 BTC but I couldn’t do it and I have noticed that my 2BTC was moved from my wallet account to + Unconfirmed account. I have no idea why did that happen and I am thinking its some software problem.

I would really appreciate if someone could help me with this issue. 

![screen shot 2016-07-14 at 9 38 25 pm](https://cloud.githubusercontent.com/assets/19391464/16841565/628ea90e-4a0c-11e6-86cb-c115e0a8cff4.png)

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
