### ISSUE TITLE
Can't access my bitcoins - all the transactions turned UNCONFIRMED

### ISSUE THREAD

**Issue by Tomsell** [keepkey/multibit-hd#912]
Today all of my bitcoins turned to unconfirmed. I have tried to repair the wallet several times, but I still can't access my bitcoins. Here is my wallet how it looks at the moment:
![screenphoto_2016-07-25 - 11 17 35](https://cloud.githubusercontent.com/assets/20639058/17096634/a9402886-525a-11e6-8c59-16233a2a83c2.png)

PLEASE HELP ME ASAP AS I NEED MY BTC IMMEDIATELY!

**Comment by Tomsell** [comment]
Hello?! Can anyone help me please??

**Comment by dstanchfield** [comment]
Please write in to support@keepkey.com so that a ticket is created.  We can help you with this issue there.  I am going to go ahead and close this.
