### ISSUE TITLE
wallet btc moved back to unconfirmed column

### ISSUE THREAD

**Issue by khaptane** [keepkey/multibit-hd#913]
my wallet was loaded with  a confirmed $63  from which i sent $10 but a day after i logged into my wallet to only see that the remaining $53 has now moved to the unconfirmed amount column amd i cant use my btc. it has been about 24 hours now but it still hasn't been resolved

![multibit](https://cloud.githubusercontent.com/assets/20680213/17171814/4992d408-53c0-11e6-97d9-651e4a690503.PNG)

Bug report
  Operating System: windows  10
  MultiBit HD Version: MultiBit HD Version 0.3.x
  Steps to replicate the problem:
  1. Add your steps here

**Comment by reegoon** [comment]
Go to manage wallet and repair your wallet. Should work.

**Comment by khaptane** [comment]
Thanks very much. it worked
