### ISSUE TITLE
Unconfirmed transactions and wallet repair does not fix it

### ISSUE THREAD

**Issue by pobalopalous** [keepkey/multibit-hd#916]
I have a lot of transactions that were previously confirmed now showing up as unconfirmed. Wallet repair has been attempted a number of times and it the issue does not get fixed. What other options are available to get the correct balance shown?

**Comment by kliyer** [comment]
Hi pobalopalous sorry to hear about your unconfirmed transactions. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
