### ISSUE TITLE
Transaction is receiving type and balance is 0

### ISSUE THREAD

**Issue by robinhan** [keepkey/multibit-hd#918]
Just like the issue:
https://github.com/keepkey/multibit-hd/issues/862
I reproduce this issue .
And as you said ,we find the status is : Unknown transaction status 

![image](https://cloud.githubusercontent.com/assets/1070083/17687362/f7c57fda-63a6-11e6-81a6-0f3e8bbb0dc0.png)

**Comment by kliyer** [comment]
Hi robinhan sorry to hear about your unconfirmed transactions.I would suggest you contact the KeepKey Support Desk @ https://keepkey.freshdesk.com/support/solutions
