### ISSUE TITLE
Cannot send transaction missing 5000 satoshi despite enough amount for fee

### ISSUE THREAD

**Issue by SMH17** [keepkey/multibit-hd#920]
I have tried to empty my wallet sending all the amount to another address

- i have set the transaction fee to lower 5000 satoshi
- subtracted the 5000 satoshi per Kb to the total bitcoin amount

get the error " The send transaction could not be created, missing 5000 satoshi"

This is a critical bug that means Multibit HD doesn't calculate correctly the amount during the transaction processing checks or the wallet corruption happened to my wallet days ago (for another reported critical bug that has affected many others users https://github.com/keepkey/multibit-hd/issues/909 ) has not been completely repaired during the wallet repair task.

**Comment by kliyer** [comment]
Hi SMH17 sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.

**Comment by pattoM** [comment]
Why would something be in the market with such bugs not yet fixed?
