### ISSUE TITLE
What's the derivation path I should use to get the master private key from a MBHD seed

### ISSUE THREAD

**Issue by YvonFortier** [keepkey/multibit-hd#927]
Hello!

Would greatly appreciate it if you could help out. I know it's not part of an use case, but I have to get my xpub from my seed. Could you tell me how to derive it? I've tried several different paths that I found in several documents and forum posts, but I can't seem to get it right. Thanks.

**Comment by bgok** [comment]
Please contact KeepKey support at https://support.keepkey.com/support/home. They can help you solve this issue.

Thanks.
