### ISSUE TITLE
Sent all my coins to unconfirmed

### ISSUE THREAD

**Issue by ovegatron** [keepkey/multibit-hd#929]
I made a transaction that was half the sum of my wallet and it took the entire contents of my wallet and put them in unconfirmed with nothing in the transactions history

**Comment by bgok** [comment]
The unconfirmed amount was included in the transaction and will be returned as change when the transaction is confirmed. The transaction will show up in history when it is confirmed. If you have any further questions or issues, please contact support@keepkey.com.

**Comment by ovegatron** [comment]
![walletpain](https://cloud.githubusercontent.com/assets/22533645/18977440/dd75b360-867f-11e6-80b6-12b2c44e1b5f.jpg)

**Comment by ovegatron** [comment]
Does that look normal ^

**Comment by bgok** [comment]
Probably shouldn't post stuff like that here. It is better to contact support if you need help.
