### ISSUE TITLE
Bitcoin Transfer

### ISSUE THREAD

**Issue by Live64** [keepkey/multibit-hd#931]
Bug report
  Operating System: Windows XP
  MultiBit Version: 0.5.16
  Steps to replicate the problem: I can not transfer funds to the wallet Xapo
3Am98EaKbTeDrFFnwtSArDYHPfeLqh2eeb

**Comment by kliyer** [comment]
Hi Live64 sorry to hear you are facing issues with MulitBit. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
