### ISSUE TITLE
Missing Coins

### ISSUE THREAD

**Issue by cdastewart** [keepkey/multibit-hd#933]
I have about 12 coins missing from the balance in my wallet. I haven't opened it up for months but when I opened it a few days ago, It intially had my full balance with only the smaller balance available to spend. I reset the blockchain and now it has the smaller balance only. The transaction history shows I haven't spent them. Where are they? Has someone stolen them from me?

**Comment by bgok** [comment]
@cdastewart I'm sorry to hear that you are having issues with Multibit. It is unlikely that your coins were stolen. We have seen some issues recently where balances aren't being reported correctly. Your best bet is to contact KeepKey support at https://www.keepkey.com/support/get-started/. The support desk will be happy to help you troubleshoot the issue and make suggestions on how to address it.

Thanks.

**Comment by cdastewart** [comment]
Thanks but I'm using an old version of Multibit. 0.5.15. Not sure how I can get the keys transferred to the new version.

**Comment by cdastewart** [comment]
The old version was before keepkey. Will they still help? I just opened it again and even more coins have gone from my spendable balance.

**Comment by bgok** [comment]
KeepKey supports all versions of Multibit. They will help you figure out how to transfer your balance to another wallet.
